version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    networks:
      - api-network

  api:
    build: .
    container_name: typescript-api
    env_file:
      - .env.local
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    networks:
      - api-network

networks:
  api-network:
